# Generated by Django 3.0.7 on 2022-03-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0006_auto_20220307_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
