# Generated by Django 3.0.7 on 2022-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0007_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eCompany',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
