# Generated by Django 3.0.7 on 2022-04-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0008_auto_20220401_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empcode',
            field=models.IntegerField(blank='True', null='True', unique='True'),
            preserve_default='True',
        ),
    ]
