# Generated by Django 3.0.7 on 2022-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0009_employee_empcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.IntegerField(blank='True', null='True', unique='True'),
            preserve_default='True',
        ),
    ]
