# Generated by Django 3.0.7 on 2022-02-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
