# Generated by Django 3.0.7 on 2022-02-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('informations', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, null=True)),
                ('task_goal', models.CharField(blank=True, max_length=200)),
                ('task_duration', models.IntegerField(default=1)),
                ('task_informations', models.CharField(blank=True, max_length=200)),
                ('task_done', models.BooleanField(default=False)),
                ('task_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mirai.Employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_tasks', models.ManyToManyField(to='mirai.Task')),
            ],
        ),
    ]
