# Generated by Django 3.0.7 on 2022-03-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0004_day_goal_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_sett',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mirai.Employee'),
        ),
    ]
