# Generated by Django 3.0.7 on 2022-03-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0005_goal_goal_sett'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_sett',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_goal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_informations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_user',
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mirai.Employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskname',
            field=models.CharField(default='', max_length=50, primary_key='true', serialize=False, unique='true'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
